services:
  tidawnloader:
    image: ghcr.io/alexjonker/tidawnloader:main
    container_name: tidawnloader
    restart: unless-stopped
    ports:
      - "4675:8080"
    volumes:
      # Replace /DATA/AppData/tidawnloader/Downloads with the path where your jellyfin music library is located.
      - /DATA/AppData/tidawnloader/Downloads:/Downloads
    environment:
      - DownloadPath=/Downloads