services:
  mariadb:
    container_name: mariadb-tidawnloader
    image: mariadb:latest
    restart: unless-stopped
    environment:
      MARIADB_ROOT_PASSWORD: changeme
      TZ: Europe/Amsterdam
    volumes:
      - /DATA/AppData/tidawnloader/mariadb:/var/lib/mysql
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      start_period: 10s
      interval: 10s
      timeout: 5s
      retries: 3

  tidawnloader:
    image: ghcr.io/alexjonker/tidawnloader:main
    container_name: tidawnloader
    restart: unless-stopped
    depends_on:
      mariadb:
        condition: service_healthy
    ports:
      - "4675:8080"
    volumes:
      # Replace /DATA/AppData/tidawnloader/Music with the path where your jellyfin music library is located.
      - /DATA/AppData/tidawnloader/Music:/Music
    environment:
      - DownloadPath=/Music
      - DB__host=mariadb
      - DB__user=root
      - DB__password=changeme